#!/bin/bash
# In this script, it is called by srun, all nodes will execute
# 
SIF=/work/TWCC_cntr/pytorch_22.01-py3.sif
SINGULARITY="singularity run --nv $SIF"

NNODES=$5
N_GPUS=$6
MASTER_PORT=$7

export CMD=" \
    train.py --batch_size 128 --epochs 5 --lr 0.01
    "


##  torchrun @ singularity
CUR_HOST=`/bin/hostname -s`

export LAUNCHER0="torchrun\
    --nproc_per_node $N_GPUS \
    --nnodes $NNODES --node_rank=0 \
    --master_addr $1 --master_port $MASTER_PORT \
    "
export LAUNCHER1="torchrun \
    --nproc_per_node $N_GPUS \
    --nnodes $NNODES --node_rank=1 \
    --master_addr $1 --master_port $MASTER_PORT \
    "
export LAUNCHER2="torchrun \
    --nproc_per_node $N_GPUS \
    --nnodes $NNODES --node_rank=2 \
    --master_addr $1 --master_port $MASTER_PORT \
    "
export LAUNCHER3="torchrun \
    --nproc_per_node $N_GPUS \
    --nnodes $NNODES --node_rank=3 \
    --master_addr $1 --master_port $MASTER_PORT \
    "


if [ $CUR_HOST == "$1" ]; then
    $SINGULARITY $LAUNCHER0 $CMD
    echo "$SINGULARITY $LAUNCHER0 $CMD">> tmp.log
elif [ $CUR_HOST == "$2" ]; then
    $SINGULARITY $LAUNCHER1 $CMD
    echo "$SINGULARITY $LAUNCHER1 $CMD">> tmp.log
elif [ $CUR_HOST == "$3" ]; then
    $SINGULARITY $LAUNCHER2 $CMD
    echo "$SINGULARITY $LAUNCHER2 $CMD">> tmp.log
elif [ $CUR_HOST == "$4" ]; then
    $SINGULARITY $LAUNCHER3 $CMD
    echo "$SINGULARITY $LAUNCHER3 $CMD">> tmp.log
fi
