#!/bin/bash

SIF=/work/TWCC_cntr/pytorch_22.01-py3.sif
SINGULARITY="singularity run --nv $SIF"

NNODES=4
N_GPUS=2

MASTER_ADDR=`/bin/hostname -s`
MASTER_PORT=41234

export LAUNCHER0="torchrun\
    --nproc_per_node $N_GPUS \
    --nnodes $NNODES --node_rank=0 \
    --master_addr $1 --master_port $MASTER_PORT \
    "
export LAUNCHER1="torchrun \
    --nproc_per_node $N_GPUS \
    --nnodes $NNODES --node_rank=1 \
    --master_addr $1 --master_port $MASTER_PORT \
    "
export LAUNCHER2="torchrun \
    --nproc_per_node $N_GPUS \
    --nnodes $NNODES --node_rank=2 \
    --master_addr $1 --master_port $MASTER_PORT \
    "
export LAUNCHER3="torchrun \
    --nproc_per_node $N_GPUS \
    --nnodes $NNODES --node_rank=3 \
    --master_addr $1 --master_port $MASTER_PORT \
    "
export CMD=" \
    train.py --batch_size 128 --epochs 5 --lr 0.01
    "

if [ $MASTER_ADDR == "$1" ]; then
    $SINGULARITY $LAUNCHER0 $CMD
elif [ $MASTER_ADDR == "$2" ]; then
    $SINGULARITY $LAUNCHER1 $CMD
elif [ $MASTER_ADDR == "$3" ]; then
    $SINGULARITY $LAUNCHER2 $CMD
elif [ $MASTER_ADDR == "$4" ]; then
    $SINGULARITY $LAUNCHER3 $CMD
fi
